In [1]:
# tensores 
# Autor: Anderson Berg
import numpy as np



In [3]:
# tensor 0D
x = np.array(12)
print(x)
print(x.ndim)

12
0


In [11]:
# tensor 1D
x = np.array([12, 3, 6, 14, 7]) 
print(x)
print(x.shape)
print(x.ndim)


[12  3  6 14  7]
(5,)
1


In [10]:
# tensor 2D
x = np.array([[5, 78, 2, 34, 0],
             [6, 79, 3, 35, 1]])

print(x)
print(x.shape)
print(x.ndim)


[[ 5 78  2 34  0]
 [ 6 79  3 35  1]]
(2, 5)
2


In [13]:
# tensor 3D
x = np.array([[[5, 78, 2, 34, 0],
             [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]],
             [[5, 78, 2, 34, 0],
             [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]],
             [[5, 78, 2, 34, 0],
             [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]]])


print(x.shape)
print(x.ndim)

(3, 3, 5)
3


In [21]:
x  = np.array([[0,1],
               [2,3],
               [4,5],
               [6,7],
               [8,9]])

print(x.shape)
print(x.ndim)

y = x.reshape((10,1))
print(y.shape)

(5, 2)
2
(10, 1)
